### PR TITLE
Laravel 6 support - I didn't test it yet

### PR DESCRIPTION
**Pull request by elreco**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `development` branch, _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All PHPUnit tests are passing
- [ ] New/updated tests are included (if applicable)

**Other information:**

### CODE REVIEW

**Comment by elreco** [comment]
Hello,

I will test it on a fresh laravel 6 project. I keep you update.

**Comment by elreco** [comment]
image

It seems to work !

**Comment by supergrecko** [comment]
Thanks for your contribution :)

**Comment by supergrecko** [comment]
Will be reverting this as it broke on non-laravel systems. Will find an alternative way of using the env helper.

**Pull request merged**
